services:
  # Main blockchain CLI service
  private-blockchain-cli:
    image: private-blockchain-cli:${VERSION:-latest}
    container_name: private-blockchain-cli
    volumes:
      - ./blockchain-data:/data
      - ./backups:/backups
    environment:
      - JAVA_OPTS=-Xmx512m
      - TZ=Europe/Madrid
    command: ["status", "--detailed"]
    profiles: ["default"]

  # Interactive CLI for manual operations
  private-blockchain-interactive:
    image: private-blockchain-cli:${VERSION:-latest}
    container_name: private-blockchain-interactive
    volumes:
      - ./blockchain-data:/data
      - ./backups:/backups
    environment:
      - JAVA_OPTS=-Xmx512m
      - TZ=Europe/Madrid
    stdin_open: true
    tty: true
    entrypoint: ["/usr/bin/zsh"]
    profiles: ["interactive"]

  # Automated backup service
  private-blockchain-backup:
    image: private-blockchain-cli:${VERSION:-latest}
    container_name: private-blockchain-backup
    volumes:
      - ./blockchain-data:/data
      - ./backups:/backups
    environment:
      - JAVA_OPTS=-Xmx256m
      - TZ=Europe/Madrid
    entrypoint: ["zsh", "-c"]
    command: ["java -jar /app/blockchain-cli.jar export /backups/backup_$$(date +%Y%m%d_%H%M%S).json"]
    profiles: ["backup"]

  # Chain validation service
  private-blockchain-validator:
    image: private-blockchain-cli:${VERSION:-latest}
    container_name: private-blockchain-validator
    volumes:
      - ./blockchain-data:/data
    environment:
      - JAVA_OPTS=-Xmx256m
      - TZ=Europe/Madrid
    command: ["validate", "--detailed", "--json"]
    profiles: ["validate"]

volumes:
  blockchain-data:
    driver: local
  backups:
    driver: local
