name: Debug Build Step by Step

on:
  workflow_dispatch:
  push:
    branches: [ main, master, develop ]

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout CLI code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Show environment info
      run: |
        echo "=== ENVIRONMENT ==="
        java -version
        mvn -version
        pwd
        ls -la
    
    - name: Try to clone core repository
      run: |
        echo "=== CLONING CORE ==="
        git clone https://github.com/${{ github.repository_owner }}/private-blockchain.git ../private-blockchain
        echo "Clone successful, checking content:"
        ls -la ../private-blockchain/
      continue-on-error: true
    
    - name: Try to build core
      run: |
        echo "=== BUILDING CORE ==="
        cd ../private-blockchain
        mvn clean install -DskipTests -X
        echo "Core build completed, checking local repository:"
        ls -la ~/.m2/repository/com/rbatllet/ || echo "No rbatllet artifacts found"
      continue-on-error: true
    
    - name: Check CLI dependencies
      run: |
        echo "=== CLI DEPENDENCIES ==="
        mvn dependency:tree
        echo ""
        echo "=== TRYING COMPILE ==="
        mvn clean compile -X
      continue-on-error: true
    
    - name: Check what was created
      run: |
        echo "=== TARGET CONTENT ==="
        ls -la target/ || echo "No target directory"
        echo ""
        echo "=== ALL FILES IN PROJECT ==="
        find . -name "*.jar" -o -name "*.class" | head -20
    
    - name: Try minimal package
      run: |
        echo "=== TRYING PACKAGE ==="
        mvn package -DskipTests -X
      continue-on-error: true
    
    - name: Final check
      run: |
        echo "=== FINAL STATE ==="
        echo "Target directory:"
        ls -la target/ || echo "No target directory"
        echo ""
        echo "All JAR files:"
        find . -name "*.jar" || echo "No JAR files found"
        echo ""
        echo "Maven repository:"
        find ~/.m2/repository -name "*.jar" | grep rbatllet || echo "No rbatllet JARs in Maven repo"