name: Release CLI

on:
  push:
    tags:
      - 'cli-v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout CLI code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install ZSH
      run: |
        sudo apt-get update
        sudo apt-get install -y zsh
      shell: bash
        
    - name: Checkout and build core blockchain dependency
      run: |
        echo "Cloning and building core blockchain for release..."
        git clone https://github.com/${{ github.repository_owner }}/private-blockchain.git ../private-blockchain
        cd ../private-blockchain
        mvn clean install -DskipTests -q
        echo "Core blockchain installed to local repository"
      shell: zsh {0}
    
    - name: Run CLI tests
      run: mvn clean test
      shell: zsh {0}
    
    - name: Build CLI JARs
      run: mvn package
      shell: zsh {0}
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/cli-}" >> $GITHUB_OUTPUT
      shell: zsh {0}
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: cli-${{ steps.get_version.outputs.VERSION }}
        name: CLI Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Private Blockchain CLI ${{ steps.get_version.outputs.VERSION }}
          
          Command Line Interface for Private Blockchain operations.
          
          ## Download Options
          - **blockchain-cli.jar**: Executable CLI JAR (Maven Shade - ~40MB - recommended)
          - **blockchain-cli-assembly-jar-with-dependencies.jar**: Alternative executable JAR (Maven Assembly - ~40MB)
          - **private-blockchain-cli-${{ steps.get_version.outputs.VERSION }}.jar**: Lightweight JAR (requires dependencies - ~53KB)
          
          ## Usage
          ```zsh
          #!/usr/bin/env zsh
          
          # Using the CLI (recommended)
          java -jar blockchain-cli.jar --help
          
          # Example commands
          java -jar blockchain-cli.jar status                     # Check blockchain status
          java -jar blockchain-cli.jar add-key "Alice" --generate # Generate and add a new key
          java -jar blockchain-cli.jar add-block "Block data" --signer "Alice" # Add a new block
          java -jar blockchain-cli.jar list-keys --detailed      # List all authorized keys
          java -jar blockchain-cli.jar validate --detailed       # Validate blockchain integrity
          java -jar blockchain-cli.jar export /path/to/backup.json # Export blockchain to JSON
          java -jar blockchain-cli.jar search "search term"       # Search blocks by content
          ```
          
          ## Requirements
          - Java 21 or higher
          - No additional dependencies needed (all included in main JARs)
        files: |
          target/blockchain-cli.jar
          target/blockchain-cli-assembly-jar-with-dependencies.jar
          target/private-blockchain-cli-${{ steps.get_version.outputs.VERSION }}.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}