name: Release CLI

on:
  push:
    tags:
      - 'cli-v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout CLI code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Download latest core blockchain JAR from releases
      run: |
        echo "Downloading latest privateBlockchain JAR..."
        LATEST_RELEASE=$(curl -s "https://api.github.com/repos/${{ github.repository_owner }}/privateBlockchain/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        if [ ! -z "$LATEST_RELEASE" ]; then
          echo "Found release: $LATEST_RELEASE"
          curl -L -o private-blockchain.jar "https://github.com/${{ github.repository_owner }}/privateBlockchain/releases/download/$LATEST_RELEASE/private-blockchain-1.0.0-jar-with-dependencies.jar"
        else
          echo "ERROR: No core blockchain releases found! Please create a release for privateBlockchain first."
          exit 1
        fi
    
    - name: Install core JAR to local Maven repository
      run: |
        mvn install:install-file \
          -Dfile=private-blockchain.jar \
          -DgroupId=com.rbatllet \
          -DartifactId=private-blockchain \
          -Dversion=1.0.0 \
          -Dpackaging=jar
    
    - name: Run CLI tests
      run: mvn clean test
    
    - name: Build CLI JAR
      run: mvn clean package
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/cli-}" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: cli-${{ steps.get_version.outputs.VERSION }}
        name: CLI Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Private Blockchain CLI ${{ steps.get_version.outputs.VERSION }}
          
          Command Line Interface for Private Blockchain operations.
          
          ## Download Options
          - **blockchain-cli.jar**: Executable CLI JAR (Maven Shade - recommended)
          - **blockchain-cli-assembly-jar-with-dependencies.jar**: Alternative executable JAR (Maven Assembly)
          
          ## Usage
          ```bash
          # Using the CLI
          java -jar blockchain-cli.jar --help
          
          # Example commands
          java -jar blockchain-cli.jar create-wallet
          java -jar blockchain-cli.jar send-transaction --from <address> --to <address> --amount <amount>
          java -jar blockchain-cli.jar balance --address <address>
          ```
          
          ## Requirements
          - Java 21 or higher
          - No additional dependencies needed (all included)
          
          ## Dependencies
          Built against privateBlockchain release: ${{ env.CORE_RELEASE }}
        files: |
          target/blockchain-cli.jar
          target/blockchain-cli-assembly-jar-with-dependencies.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}